version: '3.9'
services:
    api:
      image: lcubestudios/messagingapp-api
      container_name: messagingapp-api
      build:
         context: '.'
      # volumes:
      #   - ./app/:/var/www/html
      env_file:
        - ./.env
      environment:
        - DB_HOST=database
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_PORT=5432
        - DB_NAME=${DB_NAME}
      ports:
        - 80:80
        - 443:443
      depends_on:
        - db

    database:
      image: postgres:14
      container_name: messagingapp-db
      ports:
        - "${DB_PORT}:5432"
      restart: always
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
      volumes:
        - ./postgres-schema/messagingapp.sql:/docker-entrypoint-initdb.d/messagingapp.sql
        - ./postgres-data:/var/lib/postgresql/data
    
    pgadmin:
      container_name: messagingapp-phppgadmin
      image: bitnami/phppgadmin
      environment:
        - DATABASE_HOST=database
      ports: 
        - "8080:8080"
      depends_on:
        - db
